title: Carlson Home
views:
  - title: Home
    cards:
      - type: media-control
        entity: media_player.entryway_speaker

      - type: media-control
        entity: media_player.home_group

      - type: media-control
        entity: media_player.home_only

      - type: media-control
        entity: media_player.kitchen_speaker

      - type: media-control
        entity: media_player.loft_speaker

      - type: media-control
        entity: media_player.loft_wall

      - type: media-control
        entity: media_player.shield

      - type: media-control
        entity: media_player.soundbar

      - type: entities
        title: Automations
        show_header_toggle: true
        entities:
          - automation.double_tap_down
          - automation.double_tap_up
          - automation.heating_pad_off
          - automation.heating_pad_on
          - automation.motion_light
          - automation.triple_tap_down
          - automation.triple_tap_up

      - type: entities
        title: Binary Sensor
        show_header_toggle: true
        entities:
          - binary_sensor.aeotec_zw089_recessed_door_sensor_gen5_sensor_2

      - type: entities
        title: Cover
        show_header_toggle: true
        entities:
          - cover.garage_door

      - type: entities
        title: Fan
        show_header_toggle: true
        entities:
          - fan.master_fan

      - type: entities
        title: Groups
        show_header_toggle: true
        entities:
          - group.all_automations
          - group.all_covers
          - group.all_fans
          - group.all_lights
          - group.all_switches
          - group.carlson
          - group.master
          - group.multisensor_1
          - group.system

      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.led
          - light.master_dimmer_level

      - type: entities
        title: Sensors
        show_header_toggle: true
        entities:
          - sensor.dexcom
          - sensor.feels_like
          - sensor.humidity
          - sensor.load_15m
          - sensor.load_1m
          - sensor.load_5m
          - sensor.memory_free
          - sensor.pir
          - sensor.processor_use
          - sensor.temperature

      - type: entities
        title: Switchs
        show_header_toggle: true
        entities:
          - switch.master_bathroom_switch
          - switch.master_bedroom_switch
          - switch.master_shower_switch
          - switch.master_toilet_switch
          - switch.outdoor_switch
          - switch.wake_on_lan

      - type: entities
        title: Zwaves
        show_header_toggle: true
        entities:
          - zwave.aeotec_zw089_recessed_door_sensor_gen5_2
          - zwave.aeotec_zw090_zstick_gen5_us
          - zwave.ge_12720_outdoor_smart_switch
          - zwave.ge_12722_onoff_relay_switch
          - zwave.ge_12722_onoff_relay_switch_2
          - zwave.ge_12722_onoff_relay_switch_3
          - zwave.ge_12730_fan_control_switch
          - zwave.master_dimmer
          - zwave.master_light