title: My Lovely Home Automation
views:

  - title: Home
    cards:
      - id: camera_front_door
        type: picture-entity      
        title: Front Door
        entity: camera.front_door
        camera_image: camera.front_door
        show_info: true
        tap_action: dialog


  - tab_icon: mdi:settings
    name: Debugging
    cards:
      - type: entity-filter
        filter: [{}]
        card_config:
        title: All entities